### ISSUE TITLE
Automatic Authentication of Users

### ISSUE THREAD

**Issue by gigabytedevelopersinc** [andOTP/andOTP#107]
Well, I setup PIN mode for authentication and I must say, it is just overkill, love it but a suggestion to help enhance it is, for the PIN, there should be a limit (probably between 4-10), then for the password type of authentication, you could as well set a limit too. Well, the password can be limitless (your choice), but I strongly recommend setting a limit for the PIN mode.
That's my first suggestion!

Then here comes my second, most important and major suggestion.
After the PIN/Password has been set, I noticed that on the page that requests for the user's authentication (when the app is run), there's no `NEXT` or `ENTER` or `GO` button in that window except for the user's installed keyboard, this doesn't seem right to me because I was actually caught up in the loop asking myself where the `GO` button is on the screen and where exactly am I to click in order to continue. To be honest, most apps I've seen in recent times that have some kind of security feature, they have a `CONTINUE` button that is grayed out if nothing has been entered in the Password/PIN box and only becomes visible when the minimum or maximum number of digits has been entered in the box. Lets take for example: U set the limit for PIN authentication to 4 digits and a user's authentication PIN is `5050`, on the authentication page, the `GO` or `CONTINUE` button should be grayed out/deactivated even if the user enters 5 or enters 50 or enters 505, the button should only become visible and clickable after the user has inputted up to 4 digits.

I would have even suggested not to add a button at all, instead there should be some kind of automatic validation that automatically brings the user to the MainActivity after the right 4 digit pin has been inputted, lets say my PIN is 5050, if I input 5051 (probably on purpose or by mistake), it should automatically prompt me that the PIN i entered is wrong/incorrect, then if I input it correctly, it should automatically grant me access...
This might be a lot of work or I might not even have explained my suggestions well, all that am saying is **"there just has to be some kind of limit (minimum and maximum) and a security validation when authenticating a user"**

**Comment by flocke** [comment]
I agree with the point about an additional button to submit the PIN / password. In fact this has already been discussed in #87 and will be included in the next release.

A character limit should be easily enough. I don't see much point in having an upper limit (if the user wants to set a ridiculously long password it is his problem in the end). But I will think about a minimum length (4 seems good for PIN, I would suggest 6 or 8 for a password).

The problem I have with automatically unlocking once the correct password is entered is that we would have to store the length of the password in the settings and check once the entered password reaches that length. Checking after each entered character would slow down the app significantly due to the method of storing and validating the password we use. Storing the length on the other hand is in my eyes a serious security problem, as it already gives a possible attacker a first clue as to what the password could be.

**Comment by gigabytedevelopersinc** [comment]
Great! A minimum limit of 4 for PIN and 6 for password seems just right! 👍👌
Well, for the automatic unlocking the moment the correct password is recognized would have been really overkill, but anyways, we all want to best for andOTP, so anything that in turn results to reduced performance would be a No No for me too (no matter how awesome it would be except there's a way to curtail the performance issue it would cause), well, lets just leave that aside for now! 
A GO or CONTINUE or PROCEED or SUBMIT (Kikikikiki! 😂 😂 😂! Don't mind me, am just giving ideas for possible words to use, u make your choice from those) button would be just fine! 👌👍
