### ISSUE TITLE
Suggestion: Remove fork relationship

### ISSUE THREAD

**Issue by max-wittig** [andOTP/andOTP#145]
I think that andOTP is so much farther ahead of the original project. Maybe it's time to recognize it as it's own project.  This would maybe also attract new contributors to andOTP, as it's more than a fork now. 

What do you think about this suggestion?

**Comment by flocke** [comment]
I like the idea, bit I don't know how to remove the fork status without losing everything (followers, issue history, ...).

**Comment by enwokoma** [comment]
Well, I love the idea, I love the suggestion, it ain't so bad but I wouldn't be in support of this! Yes, andOTP has gone very far in development, far ahead of the original fork, but still, it's not right to just wake up and remove the fork that andOTP has from the original project because this would mean that andOTP was made from scratch and this clearly is a misleading information to people and I think that would be violating some licenses! 
Removing the fork might not be so bad, but please, still leave the section in the About Page of andOTP that references the original developers of the main project fork because, no matter how much development goes on within andOTP, the truth still remains that that the codebase and original app idea for andOTP was still gotten from [otp-authenticator](https://github.com/0xbb/otp-authenticator)

I too have a side project called [CometOTP](https://play.google.com/store/apps/details?id=com.gigabytedevelopersinc.app.CometOTP) made from the codebase of andOTP, there's no fork because it skipped my mind, but I still left a reference to the developer of andOTP in the About Activity of CometOTP as I and my team had no plans of calling what's not ours ours! We just can't come and claim CometOTP was made from ground-up!

**Comment by enwokoma** [comment]
and Yea! That's true! @flocke said something now! Removing the fork might not be so bad after all but removing it without losing data linked to Project andOTP is something not so sure about!

**Comment by flocke** [comment]
I would always leave the reference in the About section and in the Readme, after all otp-authenticator is the codebase I took everything from. But now I basically rewrote 99% of the code, so I think removing the fork status (just in the github repo) would be fine. But I have no idea of how to go about this without losing everything else related to the project (followers, issues, PRs, ...).

**Comment by enwokoma** [comment]
Well, @flocke, let me do some Googling on how this is possible to achieve this (removing the fork) without losing data! 
Would get back here if I find anything (information) valuable!

**Comment by enwokoma** [comment]
Hey! @flocke Check out what I found on stackoverflow just now! See if this is helpful.
Thanks!

[Un-Fork Github Repo](https://stackoverflow.com/a/41486339/7354463)

**Comment by max-wittig** [comment]
There shouldn't be any license issues here, because the original project was MIT licensed anyway and this is too. 

Okay seems to be more difficult todo on GitHub, so might not be possible without preserving all information. On GitLab it's just a click in settings and I thought that it was the same here.

**Comment by flocke** [comment]
I wrote a short request to the Github support as suggested in the link posted by @enwokoma here https://stackoverflow.com/a/44140289. Let's see if they can help.

**Comment by flocke** [comment]
Done. After writing the support they detached my fork.
Thanks for suggesting this.
