### ISSUE TITLE
Feature request: fingerprint support

### ISSUE THREAD

**Issue by meiser79** [andOTP/andOTP#150]
I'd like to ask to support the fingerprint reader if one uses encrypted storage based on password/PIN. It would mean to be able to quickly/easily unlock the app.

Thanks in advance!

**Comment by flocke** [comment]
As far as I know this is not possible since you can't use the fingerprint directly as key.
The only thing you can do is secure a key in the Android KeyStore with fingerprint authentication.
But that would defy the purpose of the password-based encryption, which is to get rid of the KeyStore.

But I will look into it anyways, maybe I am wrong.

**Comment by aph3rson** [comment]
I know this is an old one, but I can confirm that I am able to use fingerprint (+iris) authentication by using device credentials with KeyStore encryption. This hooks in natively to the OS, and uses whatever credentials are set there.

**Comment by RichyHBM** [comment]
Yea this is only possible using the keystore, I think this should be closed now

**Comment by flocke** [comment]
Yes, sadly there is no way to use the fingerprint without internally using the KeyStore in some way. And since the password / PIN encryption was introduced to avoid using the KeyStore this is not an option.

You can switch between the two encryption methods in the settings without loosing your accounts (although I would recommend a backup in case something unexpected happens).

As you might already have read somewhere I plan to stop adding new features after the next stable release and start a rewrite from scratch. That rewrite will be designed a lot better regarding the encryption and authentication, so you will be able to use your fingerprint there without compromising losing the ability to backup.

**Comment by IzzySoft** [comment]
Thanks for the fast reply, @flocke – I just had some time on the train and figured out most by myself (a.o. that keystore is no option for me because … issue 16. So, in case you want to add it to the wiki/FAQ: I would not only recommend, but strongly suggest making a backup first or else all accounts are lost if the device is affected by issue 16 (mine is when using keystore – and it seems also when having used it once; will add that to issue 16 / wiki). So:

1. make backup (else all accounts might be lost when affected by issue 16)
1. in *settings,* switch "encryption method" (you might be asked to change the authentication method first)
1. conversion should take place automatically
1. if all your accounts disappeared, restore the backup. If they disappear again, switch back to your original encryption method and restore. If they still disappear, go to *Settings › Apps,* select *andOTP* and delete its cache and data. Then start *andOTP* again, **DO NOT chose keystore** (if that was what broke it), adjust the settings, and restore your data.

For me, the last step was needed. Not using and never having used keystore with andOTP, accounts stay. Apart from that, even with keystore and device credentials chosen, I was not offered fingerprint unlock.

----

Great news about the rewrite! Wish you all the best for it (it's always a lot of work, so I already tap my hat and bow my head). Looking forward to that!
