### ISSUE TITLE
Polish translation is outdated

### ISSUE THREAD

**Issue by GarryMoveOut** [andOTP/andOTP#151]
#### General information

* **App version:** 0.4.0.1
* **App source:** F-Droid
* **Android Version:** 5.0.2 (API 21)
* **Custom ROM:** MIUI 9

1)
Some strings are not translated mainly in settings activity but some other are also not translated. For example in `<string name="settings_title_tap_to_reveal_timeout">Timeout for tap to reveal</string>` in andOTP/app/src/main/res/values-pl-rPL/strings_settings.xml is in English.

2) 
Second thing I found is wrong string name i.e. `<string name="auth_msg_password">Wprowadź proszę hasło, aby otworzyć andOTP.</string>` string with that name don't exist in english version, but I am sure that it should be equivalent to `<string name="auth_msg_authenticate">Please authenticate to start andOTP!</string>`

It is only few samples. I'm ready to help if it is needed.

**Comment by flocke** [comment]
The translation is entirely done by the community on [Crowdin](https://crowdin.com/project/andotp), I only speak English and German.

1. If not all the strings are translated then Crowdin falls back to the English source strings, that's why there are still some English strings in the files.
2. I only update the translated strings right before a new release, so currently all of the translations are still from the last release, while the source strings have already changed. That's why there are some strings in the translations that don't exist anymore (or got renamed) in the source.

If you want to help to fix the errors you can head over to [Crowdin](https://crowdin.com/project/andotp) and work on the translation there.
