### ISSUE TITLE
Blank screen instead of settings

### ISSUE THREAD

**Issue by ARR552** [andOTP/andOTP#197]
Version 0.6.0-beta3 from fdroid
Devide: android 8.1.0
Custom rom: copperheadOS with latest security patch (june 2018)
There is an issue when i try to go to settings. When i press this button appears a blank screen and app crashes all the time.

**Comment by flocke** [comment]
Please upload a log, otherwise I can't debug this as I can't reproduce it myself.

**Comment by ARR552** [comment]
[log.txt](https://github.com/andOTP/andOTP/files/2214407/log.txt)
here is the log. Sorry for the delay. If you need something else, just let me know.

**Comment by flocke** [comment]
I think I see the problem. I will have to take a closer look on Monday, I'm not at home over the weekend.

**Comment by codethief** [comment]
For anyone else getting a blank screen instead of the settings: I just ran into this issue with AndOTP v0.9.0.1 on Android 12 right after installing the app and importing a backup from another phone running AndOTP v0.8.0. I was about to post a new bug report but clearing the app's storage and re-importing the backup seems to have fixed the issue for now.
