### ISSUE TITLE
(Feature request) Winauth support

### ISSUE THREAD

**Issue by sonho666** [andOTP/andOTP#203]
As both projects are open source, it would be great to have an option to export to Winauth (https://winauth.github.io/winauth/index.html)

Authenticator+ have an option to do this, but, as I'm trying to stay with open source apps, thought to ask here :)

Thanks

**Comment by max-wittig** [comment]
Someone could write a script to "translate" the json format of andOTP to WinAuth, but I don't think this should be implemented in andOTP directly.

**Comment by flocke** [comment]
We already had this discussion multiple times and it basically comes down to what @max-wittig said:
We won't be implementing import or export to other formats, since in our opinion this is not something a simple OTP app needs. You can always just write a script that converts the JSON backups in some other format to import in other apps.
