### ISSUE TITLE
some questions about encryption

### ISSUE THREAD

**Issue by paolostivanin** [andOTP/andOTP#295]
Hello,
I was looking into the encryption details and I have a few questions about it:

1) I see from [here](https://github.com/andOTP/andOTP/blob/master/app/src/main/java/org/shadowice/flocke/andotp/Utilities/EncryptionHelper.java#L62) that the PBKDF2 iterations can be random (even though by default 1000 is used). Is this option already available or is it something planned for the future?

2) how are you going to store the iterations number in the encrypted file? Something like `IV-iter-enc_data-tag` ?

3) right now (`v0.6.x`) the file format is: `IV-ENC_DATA-TAG` where password is `first_10_chars(PBKDF2(password, iv as salt, 1000 iterations, sha1))`, am I right?

**Comment by paolostivanin** [comment]
I just created a backup but the encryption is still using the old method (`sha256(pwd)`).
I'm a bit confused now. The code I linked above is something that will happen in the future or is it something used somewhere else?

**Comment by flocke** [comment]
There are two different encryption types used:
1. For the **internal database**: **AES/GCM/NoPadding** with a **128 bit key** and a **12 byte IV** (stored as ``IV + ENC_DATA``). The key can come either from the Android KeyStore or it is derived from the password using PBKDF2. In the second case the generated key is actually 256 bit long and only the first half is used for the encryption. The iterations for the PBKDF2 are random and the exact number is stored in the apps settings, not the encrypted file. Same with the salt, it's generated random and stored in the apps settings.
2. For the **backups**: **AES/GCM/NoPadding** with a **128 bit key** and a **12 byte IV** (before the encrypted data). The key is generated by simply using the SHA256 hash of the password (because I didn't know much about encryption when I implemented it). But this will be changed for [the rewrite](https://github.com/andOTP/andOTP/wiki/The-Rewrite) to be more secure. Same storage as for the database: ``IV + ENC_DATA``.

**Comment by paolostivanin** [comment]
Thanks for the exhaustive explanation :)
