### ISSUE TITLE
#andotp:matrix.shadowice.org is not accessible at this time.

### ISSUE THREAD

**Issue by Perflyst** [andOTP/andOTP#313]
Seems like your matrix server is down? Can you please link some alternative aliases?

**Comment by flocke** [comment]
It's true, our matrix server is down (and has been for a while now). But since there were not really a lot of matrix users in the channel and it was not really active at all I do not plan to create a new one.

That being said, if there is enough request from the users I might reconsidered. I'm gonna label the issue as "wontfix" but please comment if you still have interest in a matrix channel.

**Comment by Perflyst** [comment]
I have interest, yes. At least some kind of channel would be good, matrix xmpp irc whatever you want. If you dont want one than please remove the link to the matrix channel in the readme.

Also you dont have to host your own matrix server, if you add aliases from other home servers than this room doesn't die if just your server goes down.

**Comment by flocke** [comment]
I'm gonna remove the matrix channel from the readme soon (I'm currently traveling and won't be home till next week).

The Telegram channel is pretty active if that is an option for you. If not I'm gonna look into an alternative next week as well.

**Comment by Perflyst** [comment]
> The Telegram channel is pretty active if that is an option for you. If not I'm gonna look into an alternative next week as well.

You could even bridge the Telegram channel to matrix, for example F-Droid does the same.

**Comment by flocke** [comment]
I fixed to link in the Readme to point to our new channel.
