### ISSUE TITLE
[SUPPORT] Decryption of database

### ISSUE THREAD

**Issue by tacticalDevC** [andOTP/andOTP#322]
Hello friend!
A few days ago I made a backup of your app (not of  the secrets) and restored it again. Problem: something went wrong. Now I had to restore a backup of the secrets from a long time ago.

Well I found in the data directory of the app the key and "secrets.dat". I want to decrypt this file. Could you please be so kind and make up a small program which decrypts me the database.

tacticalDevC

**Comment by flocke** [comment]
This depends strongly on which encryption type you used for the database. Since you were unable to restore your (Titanium?) backup I assume the Android KeyStore. In that case it won't be possible to decrypt the `secrets.dat` file (you could brute force it, but with the AES256 encryption that would take multiple 100 years).
If you didn't use the KeyStore but a password and still remember that password then I might be able to write a small Python script to decrypt it, but for that you would also need the `org.shadowice.flocke.andotp_preferences.xml` file from the data directory which contains additional information on the encryption.

**Comment by tacticalDevC** [comment]
I think the encryption type doesn't matter (please correct me if I am wrong) because I got the keyfile. Could you please be so kind and write that script?
Do you need the shared preferences to write it?

**Comment by flocke** [comment]
What file do you have? The `secrets.dat` is the encrypted database, there is no keyfile.

**Comment by tacticalDevC** [comment]
I have to correct you: I have an otp.key file

**Comment by tacticalDevC** [comment]
![proof](https://i.imgur.com/5WCXpAq.png)

**Comment by flocke** [comment]
You are right, if you use the KeyStore that file exists as well. It contains the encryption key for the database but it is secured using the Android KeyStore, so we can't use it without the original KeyStore entry. And sadly those entries can't be included in backups.
So there is sadly no way to decrypt your accounts.

**Comment by tacticalDevC** [comment]
So you want to tell me that the key is encrypted by the keystore?
Fortunately I got a system backup. Do you know where these entries are stored? With that information I can get the needed key to the key to the secrets.dat file.

**Comment by flocke** [comment]
Exactly, that key is encrypted by the KeyStore.

Did you restore the backup on the same phone you took it on? Because the KeyStore entries are tied to the hardware of your phone (hardware cryptography), so you won't be able to use it if it's a different phone.

But even if it's the same phone I'm not sure it will work. For one you will need to perform the decryption on the phone itself (because of the hardware cryptography) and I don't have any deep knowledge of the KeyStore. If I find the time I will try to experiment a bit on my test phone and see if I can figure out a way to decrypt your data.

**Comment by tacticalDevC** [comment]
Yes it is the same phone. And the data partition has not been wiped so the keys should still be the same.

I can try to find a war right now so you don't have to do it. Thank you anyways for your constructive support! If I find something or have another question I'll get back to you.

**Comment by flocke** [comment]
As far as my research went, manually decrypting the database with the KeyStore is basically impossible. Closing this for now.
