### ISSUE TITLE
Bad crypto implementation?

### ISSUE THREAD

**Issue by bishtawi** [andOTP/andOTP#384]
I just saw the comments in this [Reddit thread](https://old.reddit.com/r/androidapps/comments/b45zrj/dev_aegis_authenticator_secure_two_factor/ejvioko/?context=2). 

1. Have the bad cryptography designs been addressed in the latest version? 
2. If they havnt, have they been at least documented somewhere?

**Comment by flocke** [comment]
Sadly I currently don't have the time to work on anything. So no, they have not yet been fixed. But just to make sure, the "bad implementation" is only related to the password protected backups. The database encryption is fine. They both use state of the art AES encryption. But the password derivation for the backups is lacking. It should be a quick fix but because of the missing time it hasn't been done yet. I'm open for PRs if someone else wants to work on it.

**Comment by flocke** [comment]
I'm gonna close this issue for now, since I answered the original question. But feel free to continue asking anything if you want to know more.

**Comment by flocke** [comment]
After your comment here I actually took a day of work and added a proper encryption of the password-protected backups. So the main issue from that Reddit post should be fixed in d96b0373d9db6af6363aec59bf3a32928f0c504d.

**Comment by bishtawi** [comment]
Good work @flocke!
