### ISSUE TITLE
[Information] UTC -3 Sao Paulo without Summer Time

### ISSUE THREAD

**Issue by kelvinwl** [andOTP/andOTP#404]
**EN-US**: For anyone in Brazil that had time changed automatically with the time zone, you will not be able to use your codes if you change your time manually.
If you want to use TOTP without changing your time, you will have to change your time zone to any -3 (Buenos Aires maybe?), because Brasilia original is -3, and Summer Time is -2.

**PT-BR**: Pra todos que moram no Brasil e que tiveram o horário alterado automaticamente, você não vai conseguir usar os códigos se você trocar o horário manualmente, como os tutoriais da internet estão dizendo.
Pra usar  TOTP sem trocar o horário, você vai ter que trocar o fuso horário pra algum que seja -3 (Buenos Aires é uma opção), porque o fuso de Brasília é -3, e com o horário de verão fica -2.

#### General information

* **App version:** 0.6.3.1
* **App source:** Google Play
* **Android Version:** 6.0.1

**Comment by flocke** [comment]
Thank you for the information. Yes, time is extremely important for the generation of TOTP tokens. They are calculated based on the current time, which has to be the same between the phone and the server you are trying to authenticate with. The timezone should not matter for this (since it is converted to UTC before calculating the tokens), you just have to use the correct one for your location. The easiest way in most cases is to just use automatic settings of the phone.

**Comment by flocke** [comment]
I will add an entry for non-working tokens to the FAQ and link to this issue from there.
