### ISSUE TITLE
"Backup directory" should let the user browse for a folder

### ISSUE THREAD

**Issue by 12people** [andOTP/andOTP#509]
**Is your feature request related to a problem? Please describe.**
When choosing the "Backup directory" in settings, one has to write out the path by hand.
This creates a multitude of problems:

1. It's **prone to user error**, as mistyping the path is easy and there are no checks for whether the path is valid.
2. It's **a hassle** to type the whole path. Instead of a few taps picking the directory with a file browser, the user has to type out a long path. And since the forward slash is hidden in the "more symbols" part of most keyboards, the user has to constantly switch between that and the alphanumeric keyboard part.
3. It **forces the user to study the Android directory structure**. Most don't know off the top of their head where their Nextcloud folder is, for instance.
4. It's **not accessible to non-technical users**. Don't expect someone non-technical to research the Android folder structure.

**Describe the solution you'd like**
The "Backup directory" item in Settings should open up a file browser and let the user browse for the desired directory.

**Comment by flocke** [comment]
That's already on the todo list for the next release. Originally the setting was introduced because some people were having problems with their ROMs file picker, so it intentionally got implemented without one. But I haven't had any reports on that subject and for Android 10 and above it actually won't work with just a path anymore. So for those reasons I am planing to rework that setting to use the native file picker and Androids storage access framework to be more future proof.

**Comment by 12people** [comment]
Looking forward to it!

**Comment by flocke** [comment]
Implemented in 356815d7e76bca3c63b5c6572162d46a293cd87b.
