### ISSUE TITLE
QR codes with issuer=Steam should pre-select type as Steam

### ISSUE THREAD

**Issue by rossengeorgiev** [andOTP/andOTP#510]
Hi,
I'm the author of https://github.com/ValvePython/steamctl, which can now generate a QR code for Steam. 

### Issue
When I scan the QR code generated, the entry is created with all the right parameters, except it using TOTP mode instead of Steam. I don't think there is a way to change the mode after the entry is created.

### Solution(s)

1. Accept `steam` type (e.g. `otpauth://steam/...`). This violates the [google authenticator spec](https://github.com/google/google-authenticator/wiki/Key-Uri-Format). Benefit is that the `uri` won't work for apps that don't support the new type. By default **5 digits**, instead of 6.

2. Make andotp able recognize `issuer=Steam` and select Steam instead of TOTP. Downside is that if there is ever regular TOTP for Steam, this will likely causes issues.

### Workaround

1. Manually create the entry and type the secret

### Sample QR code for testing

![image](https://user-images.githubusercontent.com/2720787/77828823-bd282c80-7115-11ea-9ea5-265ee8cefef7.png)

**Comment by flocke** [comment]
Sorry it took me a while to respond to this, but I personally would prefer the ``otpauth://steam/`` option. Like you said, it would violate Googles URI specs, but then again Steam isn't really a "default" OTP algorithm anyways so I think that would be fine.
And I think the benefit that apps which don't support Steams algorithm won't add the token when scanning the "invalid" QR code is very important. Otherwise people might scan the QR code with e.g. Google Authenticator and, since it would work and generate TOTP tokens, think everything works fine. Using ``otpauth://steam/`` would be a way to prevent that.

**Comment by rossengeorgiev** [comment]
Hi, no worries. We had a discussion with the devs of Aegis, and they agree this is the best way to implement it too. Great for the users as the same QR code will work on multiple apps. I will update my code ones this feature lands. Will Steam support still remain an experimental feature?

**Comment by flocke** [comment]
I'm not yet sure if I want to make it a standard feature. On the one side it will become considerably easier to enroll Steam in andOTP with your QR codes (at least for people who aren't afraid of the commandline), but on the other side I am afraid that there will be a lot of people complaining and opening issues because it is still not really straight forward. But that's more my problem, I think I will move forward and move it out of the experimental features in the next release.

**Comment by flocke** [comment]
Done and done. I implemented support for ``otpauth://steam/`` URIs and moved Steam out of the Special Features.

**Comment by rossengeorgiev** [comment]
Awesome! 🎉
