### ISSUE TITLE
Simplify auto backup flow

### ISSUE THREAD

**Issue by RichyHBM** [andOTP/andOTP#614]
**Is your feature request related to a problem? Please describe.**
Currently the automated backups require a number of things:

* Have write permissions
* Using date appended filenames
* Not requesting the user for the backup name
* Have valid backup directory
* Have set an encrypted backup password

This can become confusing and un-intuitive

**Describe the solution you'd like**

Not require **Using date appended filenames** and make automated backups use date appended files automatically, removing the requirement of **Not requesting the user for the backup nam**

Default **Have valid backup directory** to be something sensible, like **/sdcard/andOTP** 

And request write permissions if not already given, when setting an auto backup option. Lastly it should pop up a message if you havent set a backup password.

This whole flow ensures out of the box all you would need to do is set a backup password

**Comment by flocke** [comment]
The requirements for auto backups have been changed a lot with the storage access rework in 0.8.0.

1. Write permissions are no longer required since andOTP now uses the Storage Access Framework for everything (storage permissions have been removed from the Manifest altogether).

2. A default backup location won't be possible since the user now has to manually grant persistent access to a folder using the SAF before andOTP can use it. Setting the backup folder in the settings will do this.

3. I agree that the "ask for filename" and the "append date" option should not be relevant for the auto backups.

With that the requirements basically come down to:

1. Have a backup folder defined in the settings (which grants persistent storage access).
2. Have a backup password set.

I think that's as easy as we can get and those should be easy enough to document for the user.

**Comment by RichyHBM** [comment]
Can an app still access its external data folder? So like /sdcard/Android/Data/andOTP/... Maybe that could be the default?

**Comment by flocke** [comment]
I think this can be closed now after the SAF rework. Setting a backup folder (and with that granting persistent storage access) and a password are the minimum requirements. Those should not be changed in my opinion.
