### ISSUE TITLE
Battle.net support

### ISSUE THREAD

**Issue by namazso** [andOTP/andOTP#680]
**Is your feature request related to a problem? Please describe.**
No it isn't

**Describe the solution you'd like**
Battle.net added as an option for authenticator, like steam

**Describe alternatives you've considered**
Using a python package to get the TOTP url for it.

**Additional context**
https://hugo.barrera.io/journal/2016/11/23/using-freeotp-with-battlenet/

**Comment by flocke** [comment]
Battle.net is already supported, [check the wiki](https://github.com/andOTP/andOTP/wiki/Shared-secrets#battlenet).

But they don't officially support 3rd party authenticators, just their own app. So there is no other way than to use the Python script to get the TOTP URI because they don't provide a default method of enrollment.

**Comment by namazso** [comment]
oh my bad, i only checked issues and the app. I was thinking of including the python script's functionality into andOTP for ease of use.
Although looking at it it seems to need network stuff, so that'd require heaps of new permissions and all into the app.
