### ISSUE TITLE
Replace existing entries should default to false

### ISSUE THREAD

**Issue by RichyHBM** [andOTP/andOTP#80]
Currently the default behaviour when restoring from a backup is to wipe all entries and add the restored ones, this can cause you to lose entries if you for example added a new entry before restoring an old backup.

I think by default this should be set to false, that way the worse that can happen is you end up with duplicates (which you can remove manually)

Ideally we could have some logic to detect and not add duplicates, but for now I think defaulting that setting to false should suffice.

This should be an easy task if anyone wants to try some android development, else I'll do a PR later in the week

**Comment by flocke** [comment]
Yeah, I was thinking about that as well. I kept the default "true" because that was the behavior before I added the switch. I will switch it in the next release.

The duplicates should already be detected and removed. It all comes down to the `equals()` function of the Entry class to detect duplicates.
